// netlify/lib/access.js
// Single source of truth for all access control.
// DO NOT edit manually — generated by Admin Panel.

const { getPortalConfig } = require('./portal-config');

const ACCESS = {
  admins:     ["arth.mohan@peepalconsulting.com","anish.k@peepalconsulting.com","renjith.k@peepalconsulting.com","sambhav.m@peepalconsulting.com"],
  recruiters: ["ramya.h@peepalconsulting.com","krishna.kumar@peepalconsulting.com","aditi.kaul@peepalconsulting.com","renjith.k@peepalconsulting.com"],
  managers:   ["ravi.kant.sharma@peepalconsulting.com","ambika.s@peepalconsulting.com","shiwala.dubey@peepalconsulting.com","parv.u@peepalconsulting.com","ramakrishna.d@peepalconsulting.com","rohan.p@peepalconsulting.com","rupa.moogi@peepalconsulting.com","mayank.bajaj@peepalconsulting.com"],
  kaveri:     ["kaveri.karnam@peepalconsulting.com"],
  vijay:      ["vijay@peepalconsulting.com"],
};

const MANAGER_NAME_EMAIL = {
  'Kaveri': 'kaveri.karnam@peepalconsulting.com',
  'Ravikant': 'ravi.kant.sharma@peepalconsulting.com',
  'Ambika': 'ambika.s@peepalconsulting.com',
  'Shiwala': 'shiwala.dubey@peepalconsulting.com',
  'Parv': 'parv.u@peepalconsulting.com',
  'Ramakrishna': 'ramakrishna.d@peepalconsulting.com',
  'Rohan': 'rohan.p@peepalconsulting.com',
  'Rupa': 'rupa.moogi@peepalconsulting.com',
  'Mayank': 'mayank.bajaj@peepalconsulting.com',
  'Renjith': 'renjith.k@peepalconsulting.com',
  'kaveri': 'kaveri.karnam@peepalconsulting.com',
  'ravikant': 'ravi.kant.sharma@peepalconsulting.com',
  'ambika': 'ambika.s@peepalconsulting.com',
  'shiwala': 'shiwala.dubey@peepalconsulting.com',
  'parv': 'parv.u@peepalconsulting.com',
  'ramakrishna': 'ramakrishna.d@peepalconsulting.com',
  'rohan': 'rohan.p@peepalconsulting.com',
  'rupa': 'rupa.moogi@peepalconsulting.com',
  'mayank': 'mayank.bajaj@peepalconsulting.com',
  'renjith': 'renjith.k@peepalconsulting.com',
};

function normalizeEmail(email) {
  return String(email || '').trim().toLowerCase();
}

function normalizeName(name) {
  return String(name || '').trim().toLowerCase().replace(/\s+/g, ' ');
}

function getUserRole(email) {
  return getUserRoleFromAccess(email, ACCESS);
}

function getUserRoleFromAccess(email, access = ACCESS) {
  const e = normalizeEmail(email);
  if (!e) return 'viewer';
  if ((access.admins || []).map(normalizeEmail).includes(e))     return 'admin';
  if ((access.recruiters || []).map(normalizeEmail).includes(e)) return 'recruiter';
  if ((access.kaveri || []).map(normalizeEmail).includes(e))     return 'kaveri';
  if ((access.vijay || []).map(normalizeEmail).includes(e))      return 'vijay';
  if ((access.managers || []).map(normalizeEmail).includes(e))   return 'manager';
  return 'viewer';
}

function getManagerEmail(managerName, managerNameEmail = MANAGER_NAME_EMAIL) {
  if (!managerName) return null;
  const raw = String(managerName).trim();
  if (raw.includes('@')) return normalizeEmail(raw);
  return managerNameEmail[raw] || managerNameEmail[normalizeName(raw)] || null;
}

function isAssignedManager(email, candidate) {
  return getManagerEmail(candidate?.manager) === normalizeEmail(email);
}

function isAssignedManagerForConfig(email, candidate, config) {
  return getManagerEmail(candidate?.manager, config.MANAGER_NAME_EMAIL || MANAGER_NAME_EMAIL) === normalizeEmail(email);
}

function canViewCandidate(email, candidate) {
  const role = getUserRole(email);
  if (role === 'manager') return isAssignedManager(email, candidate);
  return role !== 'viewer';
}

function filterCandidatesForUser(email, candidates) {
  const role = getUserRole(email);
  if (role === 'manager') return candidates.filter(c => isAssignedManager(email, c));
  if (role === 'viewer')  return [];
  return candidates;
}

function getAccessFromConfig(config) {
  return config?.ACCESS || ACCESS;
}

function expandManagerNameEmail(managerNameEmail) {
  const expanded = { ...(managerNameEmail || {}) };
  for (const [name, email] of Object.entries(managerNameEmail || {})) {
    expanded[normalizeName(name)] = email;
  }
  return expanded;
}

async function getRuntimeAccessConfig() {
  const config = await getPortalConfig();
  const managerNameEmail = expandManagerNameEmail(config.MANAGER_NAME_EMAIL || MANAGER_NAME_EMAIL);
  config.MANAGER_NAME_EMAIL = managerNameEmail;
  return {
    access: getAccessFromConfig(config),
    managerNameEmail,
    adminEmails: config.ADMIN_EMAILS || config.ACCESS?.admins || ACCESS.admins,
    config,
  };
}

function canViewCandidateForConfig(email, candidate, config) {
  const role = getUserRoleFromAccess(email, getAccessFromConfig(config));
  if (role === 'manager') return isAssignedManagerForConfig(email, candidate, config);
  return role !== 'viewer';
}

function filterCandidatesForConfig(email, candidates, config) {
  const role = getUserRoleFromAccess(email, getAccessFromConfig(config));
  if (role === 'manager') return candidates.filter(c => isAssignedManagerForConfig(email, c, config));
  if (role === 'viewer') return [];
  return candidates;
}

async function getUserRoleAsync(email) {
  const { access } = await getRuntimeAccessConfig();
  return getUserRoleFromAccess(email, access);
}

async function filterCandidatesForUserAsync(email, candidates) {
  const { config } = await getRuntimeAccessConfig();
  return filterCandidatesForConfig(email, candidates, config);
}

module.exports = {
  ACCESS,
  MANAGER_NAME_EMAIL,
  canViewCandidate,
  canViewCandidateForConfig,
  filterCandidatesForUser,
  filterCandidatesForConfig,
  filterCandidatesForUserAsync,
  getManagerEmail,
  getRuntimeAccessConfig,
  getUserRole,
  getUserRoleAsync,
  getUserRoleFromAccess,
  isAssignedManager,
  isAssignedManagerForConfig,
  normalizeEmail,
};
