// netlify/lib/access.js
// Single source of truth for all access control.
// DO NOT edit manually — generated by Admin Panel.

const ACCESS = {
  admins:     ["arth.mohan@peepalconsulting.com","anish.k@peepalconsulting.com"],
  recruiters: ["ramya.h@peepalconsulting.com","krishna.kumar@peepalconsulting.com","aditi.kaul@peepalconsulting.com","renjith.k@peepalconsulting.com"],
  managers:   ["ravi.kant.sharma@peepalconsulting.com","ambika.s@peepalconsulting.com","shiwala.dubey@peepalconsulting.com","parv.u@peepalconsulting.com","ramakrishna.d@peepalconsulting.com","rohan.p@peepalconsulting.com","rupa.moogi@peepalconsulting.com","mayank.bajaj@peepalconsulting.com"],
  kaveri:     ["kaveri.karnam@peepalconsulting.com"],
  vijay:      ["vijay@peepalconsulting.com"],
};

const MANAGER_NAME_EMAIL = {
  'Kaveri': 'kaveri.karnam@peepalconsulting.com',
  'Ravikant': 'ravi.kant.sharma@peepalconsulting.com',
  'Ambika': 'ambika.s@peepalconsulting.com',
  'Shiwala': 'shiwala.dubey@peepalconsulting.com',
  'Parv': 'parv.u@peepalconsulting.com',
  'Ramakrishna': 'ramakrishna.d@peepalconsulting.com',
  'Rohan': 'rohan.p@peepalconsulting.com',
  'Rupa': 'rupa.moogi@peepalconsulting.com',
  'Mayank': 'mayank.bajaj@peepalconsulting.com',
  'Renjith': 'renjith.k@peepalconsulting.com',
  'kaveri': 'kaveri.karnam@peepalconsulting.com',
  'ravikant': 'ravi.kant.sharma@peepalconsulting.com',
  'ambika': 'ambika.s@peepalconsulting.com',
  'shiwala': 'shiwala.dubey@peepalconsulting.com',
  'parv': 'parv.u@peepalconsulting.com',
  'ramakrishna': 'ramakrishna.d@peepalconsulting.com',
  'rohan': 'rohan.p@peepalconsulting.com',
  'rupa': 'rupa.moogi@peepalconsulting.com',
  'mayank': 'mayank.bajaj@peepalconsulting.com',
  'renjith': 'renjith.k@peepalconsulting.com',
};

function normalizeEmail(email) {
  return String(email || '').trim().toLowerCase();
}

function normalizeName(name) {
  return String(name || '').trim().toLowerCase().replace(/\s+/g, ' ');
}

function getUserRole(email) {
  const e = normalizeEmail(email);
  if (!e) return 'viewer';
  if (ACCESS.admins.includes(e))     return 'admin';
  if (ACCESS.recruiters.includes(e)) return 'recruiter';
  if (ACCESS.kaveri.includes(e))     return 'kaveri';
  if (ACCESS.vijay.includes(e))      return 'vijay';
  if (ACCESS.managers.includes(e))   return 'manager';
  return 'viewer';
}

function getManagerEmail(managerName) {
  if (!managerName) return null;
  const raw = String(managerName).trim();
  if (raw.includes('@')) return normalizeEmail(raw);
  return MANAGER_NAME_EMAIL[raw] || MANAGER_NAME_EMAIL[normalizeName(raw)] || null;
}

function isAssignedManager(email, candidate) {
  return getManagerEmail(candidate?.manager) === normalizeEmail(email);
}

function canViewCandidate(email, candidate) {
  const role = getUserRole(email);
  if (role === 'manager') return isAssignedManager(email, candidate);
  return role !== 'viewer';
}

function filterCandidatesForUser(email, candidates) {
  const role = getUserRole(email);
  if (role === 'manager') return candidates.filter(c => isAssignedManager(email, c));
  if (role === 'viewer')  return [];
  return candidates;
}

module.exports = {
  ACCESS,
  MANAGER_NAME_EMAIL,
  canViewCandidate,
  filterCandidatesForUser,
  getManagerEmail,
  getUserRole,
  isAssignedManager,
  normalizeEmail,
};